// Run: node tests/design-browser.cjs (Playwright and Chromium required).
const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),assert=require('assert/strict'),path=require('path'),os=require('os');
const root=path.resolve(__dirname,'..'),artifact=name=>path.join(os.tmpdir(),name);
(async()=>{const server=http.createServer((q,r)=>{const js=q.url.split('?')[0].endsWith('intro-scenes.js');r.setHeader('Content-Type',js?'text/javascript':'text/html');r.end(fs.readFileSync(path.join(root,js?'game/intro-scenes.js':'game/index.html')));}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
for(const [width,height] of [[320,568],[390,844],[844,390],[1280,800]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/?test=1`);await page.click('#startBtn');if(await page.locator('#storySkip').isVisible())await page.click('#storySkip');
 const result=await page.evaluate(()=>{const t=__cozyTest,s=t.S();Object.assign(s,{stage:3,tut:99,coins:1e8,auto:false,season:0,mill:8,smoke:8,smelt:8,elec:8,tower:9,sites:{f1:5,p1:5,m1:5},shop:{wood:8,fish:8},shopStaff:{wood:6,fish:6},cv:{f1:1,p1:1,m1:1},pcv:{mill:1,smoke:1,smelt:1,elec:1},pst:{mill:5,smoke:5,smelt:5,elec:5},vt:{2:9,3:9},vf:{2:4,3:4},fence:4,storySeen:{1:1,2:1,3:1}});t.hero(200,390);for(const side of ['left','left','right','top','bottom'])t.spawnBear(side);t.run(.1);const bounds=el=>{const r=document.querySelector(el).getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,right:r.right,bottom:r.bottom}};const labels=t.labels(),overlaps=labels.filter(({sign:p,building:b})=>p.x-p.w/2<b.x+b.w&&p.x+p.w/2>b.x&&p.y<b.y+b.h&&p.y+p.h>b.y);return {coin:bounds('.coins'),timer:bounds('#bearChip'),meta:bounds('.meta'),radar:bounds('#raidRadar'),hint:bounds('#hint'),radarHidden:document.querySelector('#raidRadar').hidden,label:document.querySelector('#radarLabel').textContent,points:t.bears().map(b=>t.radarPoint(b.x,b.y,224,128)),labelsOverlap:overlaps,pads:t.padOverlaps(),errors:t.errs()};});
 assert.equal(errors.length,0,errors.join(';'));assert.equal(result.errors.n,0);assert(result.timer.right<=result.radar.x,'Raid timer must leave space for flush corner map');assert.equal(result.radar.right,width,'Minimap must touch the right screen edge');assert.equal(result.radar.y,0,'Minimap must touch the top screen edge');assert(Math.abs(result.timer.y+result.timer.h/2-result.coin.y-result.coin.h/2)<1,'Clock must share coin row');assert(result.coin.right<=result.timer.x&&result.timer.right<=result.meta.x,'Header badges overlap');assert(!result.radarHidden);assert(result.label.includes('5마리'));assert(result.hint.right<=result.radar.x,'Hint overlaps radar');assert(result.points.every(p=>p.x>=6&&p.x<=218&&p.y>=6&&p.y<=122));assert.equal(result.labelsOverlap.length,0);assert.equal(result.pads.length,0);
 console.log('PASS viewport',width,height,'flush corner map, separate raid clock, separate facility signs');
 if(width===1280){const arts=await page.evaluate(async()=>{const t=__cozyTest,sets={};for(const b of ['mill','smoke','smelt','elec'])sets[b]=Array.from({length:8},(_,i)=>t.workshopArt(b,i+1,3));for(const b of ['woodshop','fishshop'])sets[b]=Array.from({length:8},(_,i)=>t.facilityArt(b,i+1));sets.storage=Array.from({length:5},(_,i)=>t.storageArt(i+1));sets.tower=Array.from({length:9},(_,i)=>t.facilityArt('tower',i+1));for(const role of ['player','lumber','fisher','miner','hunter','hunter2','hunter3'])sets[role]=Array.from({length:13},(_,i)=>t.actorArt(role,role==='player'?i+1:i));
 const gallery=document.createElement('canvas');gallery.width=1040;gallery.height=Object.keys(sets).length*100;const g=gallery.getContext('2d');g.fillStyle='#e5e9dc';g.fillRect(0,0,gallery.width,gallery.height);let row=0;for(const [name,list] of Object.entries(sets)){g.fillStyle='#3f5747';g.font='11px sans-serif';g.fillText(name,4,row*100+12);for(let i=0;i<list.length;i++){const img=new Image();await new Promise(r=>{img.onload=r;img.src=list[i]});g.drawImage(img,i*80,row*100+15,80,80);}row++;}return {counts:Object.fromEntries(Object.entries(sets).map(([name,list])=>[name,{expected:list.length,actual:new Set(list).size,duplicates:list.map((v,i)=>list.indexOf(v)!==i?[list.indexOf(v),i]:null).filter(Boolean)}])),image:gallery.toDataURL()};});
 for(const [name,value] of Object.entries(arts.counts))assert.equal(value.actual,value.expected,`${name}: levels repeat`);
 const changes=await page.evaluate(async()=>{const t=__cozyTest,sets={};for(const b of ['mill','smoke','smelt','elec'])sets[b]=Array.from({length:8},(_,i)=>t.workshopArt(b,i+1,3));for(const b of ['woodshop','fishshop'])sets[b]=Array.from({length:8},(_,i)=>t.facilityArt(b,i+1));sets.tower=Array.from({length:9},(_,i)=>t.facilityArt('tower',i+1));sets.storage=Array.from({length:5},(_,i)=>t.storageArt(i+1));const ratios={};
 for(const [name,urls] of Object.entries(sets)){const frames=[];for(const url of urls){const img=new Image();await new Promise(resolve=>{img.onload=resolve;img.src=url;});const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const g=c.getContext('2d');g.drawImage(img,0,0);frames.push(g.getImageData(0,0,c.width,c.height).data);}ratios[name]=[];for(let n=1;n<frames.length;n++){const a=frames[n-1],b=frames[n];let changed=0,visible=0;for(let i=0;i<a.length;i+=4){if(a[i+3]||b[i+3]){visible++;if(Math.max(Math.abs(a[i]-b[i]),Math.abs(a[i+1]-b[i+1]),Math.abs(a[i+2]-b[i+2]),Math.abs(a[i+3]-b[i+3]))>25)changed++;}}ratios[name].push(changed/visible);}}return ratios;});
 for(const [name,ratios] of Object.entries(changes))assert(ratios.every(r=>r>=.08),`${name}: adjacent levels change too little (${ratios.join(',')})`);
 console.log('PASS all facility levels change at least 8% of visible pixels; distinct character levels');
 fs.writeFileSync(artifact('cozy-designer-gallery.png'),Buffer.from(arts.image.split(',')[1],'base64'));
 await page.evaluate(()=>{__cozyTest.S().zoomOut=true;__cozyTest.run(.05);});await page.waitForTimeout(350);await page.screenshot({path:artifact('cozy-designer-map.png')});
 }else if(width===390){await page.waitForTimeout(200);await page.screenshot({path:artifact('cozy-designer-mobile.png')});}await page.close();
}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
