// Browser verification without opening a listening socket: local assets are
// fulfilled through Playwright routing. Run with installed Playwright/Chromium.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],requested=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://cozy.test/**',async route=>{const u=new URL(route.request().url()),p=path.resolve(__dirname,'..','.'+decodeURIComponent(u.pathname));requested.push(u.pathname);if(!p.startsWith(path.resolve(__dirname,'..')+path.sep)||!fs.existsSync(p))return route.fulfill({status:404,body:'missing'});const ext=path.extname(p),types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp'};await route.fulfill({body:fs.readFileSync(p),contentType:types[ext]||'application/octet-stream'});});
 await page.goto('http://cozy.test/game/index.html?test=1');await page.waitForFunction(()=>document.querySelector('#title').classList.contains('illustrated')&&[...document.querySelectorAll('#title img')].some(i=>i.style.opacity==='1'));
 assert(!requested.some(p=>p.includes('/assets/ending/')),'Ending must stay lazy');await page.clock.install();await page.clock.runFor(4600);assert.equal(await page.locator('#introDots .current').evaluate(e=>[...e.parentNode.children].indexOf(e)),1);await page.locator('#introBack').click();assert.equal(await page.locator('#introDots .current').evaluate(e=>[...e.parentNode.children].indexOf(e)),0);await page.clock.runFor(14000);assert.equal(await page.locator('#introDots .current').evaluate(e=>[...e.parentNode.children].indexOf(e)),3);await page.clock.runFor(5000);assert(await page.locator('#title').isVisible());
 await page.locator('#introSkip').click();assert(await page.locator('#title').isHidden());assert.equal(await page.evaluate(()=>window.__cozyTest.errs().n),0);
 // Completed saved game boot must restore trophy immediately, without film fetch.
 await page.evaluate(()=>{const s=window.__cozyTest.S();s.finaleDone=1;localStorage.setItem('cozy-village-v6',JSON.stringify(s));});await page.reload();await page.waitForFunction(()=>window.__cozyTest);assert(await page.locator('#ending').isVisible());assert(await page.locator('#title').isHidden());
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.querySelector('#ending').hidden=true);await page.locator('#storyOpen').click();await page.getByRole('button',{name:'엔딩 다시 보기',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('#title img')].some(i=>i.style.opacity==='1'));assert(requested.some(p=>p.includes('/assets/ending/')));assert.equal(await page.locator('#introImageNext').evaluate(i=>getComputedStyle(i).transitionDuration),'0s');await page.locator('#introSkip').click();assert(await page.locator('#storyBox').isVisible());assert.deepEqual(errors,[]);console.log('PASS: Chromium 390x844 intro auto/back/last-hold/skip; lazy ending images; completed-save restoration; ending replay; reduced motion; zero page/runtime errors.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
