const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');const h=require('./runtime-source.cjs').readRuntime();
const e={S:{coins:1e9,shop:{wood:1,fish:1},cash:{},w:[]},agents:[{x:0,y:0}],money50:n=>Math.max(50,Math.round(n/50)*50),unitPrice:()=>50,lineOpen:()=>true,SHOPDEF:{wood:{name:'나무 가게'},fish:{name:'생선 가게'}},STALL:{wood:{x:60,y:50},fish:{x:240,y:50}},STALLFX:{},sfx(){},stat(){},celebrate(){},save(){},refreshUI(){},addFloat(){},chooseWant:()=> 'oak',ITEMS:{oak:{line:'wood',cat:'wood'}},ss:()=>20,slotPos:()=>({}),lineOf:()=>[],CUST_COL:['green'],HAIR:['brown'],Math:Object.create(Math)};e.Math.random=()=>0;vm.createContext(e);
for(const [a,b] of [['function shopStaffLevel(','var SITE_MAX='],['function serv(','/* v60 (director'],['function mkUp(','function gearDef('],['function shopStaffDef(','function shopDef('],['function shopSide(','function slotPos('],['function newCustomer(','function moveC('],['function buy(d,','/* stall stock strip:']]){const st=h.indexOf(a);vm.runInContext(h.slice(st,h.indexOf(b,st)),e);}
assert.equal(e.shopStaffLevel('wood'),0);assert.equal(e.stallCap('wood'),28);assert.equal(e.serv('wood'),1);assert.equal(e.shopRegularChance('wood'),0);assert.equal(e.customerPayment({qty:2,want:'oak',seller:'wood'},false),100);
let d=e.shopStaffDef('wood');e.buy(d,false);assert.equal(e.shopStaffLevel('wood'),0,'Still requires a world pad');
for(let l=0;l<6;l++){const before=e.S.coins,cost=d.cost();assert.equal(cost%50,0);e.buy(d,true);assert.equal(e.S.coins,before-cost);assert.equal(e.shopStaffLevel('wood'),l+1);assert.equal(e.shopClerks('wood'),Math.ceil((l+1)/2));assert.equal(e.shopShelves('wood'),Math.floor((l+1)/2));}
assert.equal(d.isMax(),true);const money=e.S.coins;e.buy(d,true);assert.equal(e.S.coins,money);assert.equal(e.stallCap('wood'),31);assert.equal(e.serv('wood'),4);assert.equal(e.shopRegularChance('wood'),.36);assert(e.shopCheckoutTime('wood')<.5);
assert.equal(e.shopStaffLevel('fish'),0,'Independent shops and old saves');const c=e.newCustomer();assert.equal(c.regular,true);assert.equal(c.qty,3);assert.equal(c.pat,(40+c.qty*1.3+6)*1.6);assert.equal(e.customerPayment({qty:10,want:'oak',seller:'wood',regular:true},false),700);assert.equal(e.customerPayment({qty:10,want:'oak',seller:'wood'},false),500);
e.S=JSON.parse(JSON.stringify(e.S));assert.equal(e.shopStaffLevel('wood'),6);delete e.S.shopStaff;assert.equal(e.shopStaffLevel('wood'),0);console.log('PASS: old saves; pad-only purchase; 50-won costs; alternating clerks/shelves; Lv6 cap; checkout; regular qty/patience/premium; independent shops and save roundtrip.');

