/* Claude GLB renders, optimized for the existing Canvas game. Metadata is
 * embedded at build time; sheets load on demand, at most two concurrently.
 * Missing/broken images return false so callers retain their original art. */
var SPRITE_ART_CAPTURE=false,SPRITE_PPU=19,SPRITES={atlas:SPRITE_DATA,img:{},state:{},queue:[],active:0};
var SPRITE_ROLE={player:'hero',lumber:'lumberjack',fisher:'fisher',miner:'miner',hunter:'hunter',hunter2:'hunter_blue',hunter3:'hunter_violet',courier:'villager',imk:'shopkeeper'};
function spritePump(){while(SPRITES.active<2&&SPRITES.queue.length){var name=SPRITES.queue.shift(),m=SPRITES.atlas[name],im=new Image();SPRITES.active++;SPRITES.img[name]=im;im.decoding='async';(function(key,image){var finished=false;function done(ok){if(finished)return;finished=true;SPRITES.state[key]=ok?'ready':'failed';SPRITES.active--;spritePump();}image.onload=function(){done(!!image.naturalWidth);};image.onerror=function(){done(false);};})(name,im);im.src='assets/sprites/'+m.file+'?v='+SPRITE_VERSIONS[name];}}
function spriteReady(name){if(!SPRITES.atlas[name])return false;if(!SPRITES.state[name]){SPRITES.state[name]='queued';SPRITES.queue.push(name);spritePump();}return SPRITES.state[name]==='ready';}
function spriteAnim(m,anim){return m.anims[anim]||m.anims.idle||m.anims.static||m.anims[Object.keys(m.anims)[0]];}
function actorSpriteAnim(a){if(a.cheerUntil>(typeof time==='number'?time:0))return 'cheer';return a.stab>0||a.aim>.12?'work':a.working?'work':((a.mv||a.moving)?'walk':'idle');}
function spriteVisible(x,y,r){if(SPRITE_ART_CAPTURE)return true;if(typeof Z!=='number'||!Z)return true;r=r||80;return x+r>=camX&&x-r<=camX+W/Z&&y+r>=camY&&y-r<=camY+SH/Z;}
function drawSprite(g,name,anim,t,x,y,ppu,flip,alpha){if(!spriteReady(name))return false;var m=SPRITES.atlas[name],a=spriteAnim(m,anim),f=0;if(a.fps&&!MOTION3D_REDUCED.matches){f=Math.floor(Math.max(0,t)*a.fps);f=a.loop?f%a.frames:Math.min(a.frames-1,f);}var s=(ppu||SPRITE_PPU)/m.ppu;g.save();if(alpha!==undefined)g.globalAlpha*=alpha;g.translate(x,y);if(flip)g.scale(-1,1);g.drawImage(SPRITES.img[name],f*m.frameW,a.row*m.frameH,m.frameW,m.frameH,-m.anchor[0]*s,-m.anchor[1]*s,m.frameW*s,m.frameH*s);g.restore();return true;}
function drawSpriteLevel(g,x,y,L,cap){if(L<=1)return;g.save();g.translate(x,y);g.fillStyle='#fff7df';g.strokeStyle='#b88b34';g.lineWidth=.6;g.beginPath();g.roundRect(-10,-4,20,8,3);g.fill();g.stroke();g.font='600 5px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillStyle='#5b441d';g.fillText('Lv'+L,0,0);g.fillStyle=L>=cap?'#f7b72e':'#2aada6';for(var i=0;i<Math.min(8,L);i++)g.fillRect(-10+i*2.5,4,2,1.8);g.restore();}
function drawFacilitySprite(g,name,x,y,w,h,L,cap,t){var m=SPRITES.atlas[name];if(!m||!spriteReady(name))return false;var ppu=m.ppu*Math.min(w/m.frameW,h/m.frameH)*(.78+.22*Math.min(1,L/(cap||8)));drawSprite(g,name,'idle',typeof time==='number'?time:0,x,y,ppu,false);drawSpriteLevel(g,x,y-h*.66,L,cap||8);return true;}
/* 2026-10-09 natural motion (render-only, kept out of the save): the walk cycle advances with the distance actually
   walked, so feet no longer slide at different speeds, and turning around squashes the sprite briefly instead of snapping. */
var STRIDE=new WeakMap(),STRIDE_PX=26;
function strideOf(a){var s=STRIDE.get(a),now=typeof time==='number'?time:0;if(!s){s={x:a.x,y:a.y,d:0,dir:a.dir||1,turn:0,lt:now};STRIDE.set(a,s);}var dt=Math.max(0,Math.min(.1,now-s.lt));s.lt=now;var dd=Math.hypot(a.x-s.x,a.y-s.y);if(dd<30)s.d+=dd;s.x=a.x;s.y=a.y;if((a.dir||1)!==s.dir){s.dir=a.dir||1;s.turn=.14;}else s.turn=Math.max(0,s.turn-dt);return s;}
function drawActorSprite(g,name,a,anim,x,y,ppu){if(!spriteReady(name))return false;var s=strideOf(a),t=anim==='walk'?s.d/STRIDE_PX*.8:(typeof time==='number'?time:0)+(a.x%7)*.1,k=s.turn>0?Math.max(.18,Math.abs(1-2*s.turn/.14)):1;
  g.save();g.translate(x,y);g.scale(k,anim==='walk'?1+Math.abs(Math.sin(s.d/STRIDE_PX*Math.PI*2))*.02:1);g.translate(-x,-y);var ok=drawSprite(g,name,anim,t,x,y,ppu,a.dir>0);g.restore();return ok;}

